#!/bin/zsh

extract-imports.sh
mvn compile dependency:build-classpath -Dmdep.outputFile=classpath.txt
classpath=$(cat classpath.txt):target/classes
jshell --class-path "$classpath" jsh/project-imports.jsh
